- name: Stop sshd via systemd
  vanduc2514.wsl_automation.wsl_systemd:
    distribution: "{{ wsl_sshd_distribution_name }}"
    name: "{{ wsl_sshd_service_name }}"
    state: stopped
  when: wsl_sshd_service_type == "systemd"
  listen: restart sshd

- name: Start sshd via systemd
  vanduc2514.wsl_automation.wsl_systemd:
    distribution: "{{ wsl_sshd_distribution_name }}"
    name: "{{ wsl_sshd_service_name }}"
    state: started
    daemon_reload: true
  when: wsl_sshd_service_type == "systemd"
  listen: restart sshd

- name: Stop sshd via sysvinit
  vanduc2514.wsl_automation.wsl_sysvinit:
    distribution: "{{ wsl_sshd_distribution_name }}"
    name: "{{ wsl_sshd_service_name }}"
    state: stopped
  when: wsl_sshd_service_type == "sysvinit"
  listen: restart sshd

- name: Start sshd via sysvinit
  vanduc2514.wsl_automation.wsl_sysvinit:
    distribution: "{{ wsl_sshd_distribution_name }}"
    name: "{{ wsl_sshd_service_name }}"
    state: started
  when: wsl_sshd_service_type == "sysvinit"
  listen: restart sshd