namespace: wsl_automation
name: wsl
version: 1.0.0
readme: README.md
authors:
  - Duc Nguyen Van <vanduc2514@gmail.com>
description: Install WSL and provision WSL Instances
license_file: LICENSE
tags:
  - wsl
  - windows
  - subsystem
  - linux
  - infrastructure
  - vm
dependencies:
  "ansible.windows": ">=1.14.0"
  "community.general": ">=9.0.0"
repository: https://git.vanduc2514.io.vn/vanduc2514/wsl-ansible-collection.git
documentation: ""
homepage: ""
issues: https://git.vanduc2514.io.vn/vanduc2514/wsl-ansible-collection/issues
build_ignore:
  - .gitignore
  - .github
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
