- name: Converge
  hosts: windows
  gather_facts: true
  vars:
    update_host_port: 9999
    inital_target_port: 8080
    policy_id: WSL-Web-Service

  roles:
    - role: vanduc2514.wsl_automation.wsl_port_forward
      vars:
        wsl_port_forward_policy_id: "{{ policy_id }}"
        wsl_port_forward_host_port: "{{ update_host_port }}"
        wsl_port_forward_target_port: "{{ inital_target_port }}"
