- name: Converge
  hosts: windows
  gather_facts: false
  tasks:
    - name: Include wsl_distribution role
      include_role:
        name: vanduc2514.wsl_automation.wsl_distribution
      vars:
        wsl_distribution_name: Ubuntu-22.04
        wsl_distribution_state: run
        wsl_distribution_arch_version: 2
        wsl_distribution_config:
          automount:
            enabled: true
            mountFsTab: true
            root: /mnt/
          boot:
            command: ""
            systemd: true
          interop:
            enabled: true
            appendWindowsPath: true
          user:
            default: "ubuntu"