- name: Converge
  hosts: windows
  gather_facts: false
  roles:
    - vanduc2514.wsl_automation.wsl_distribution
  vars:
    # Test distribution settings
    wsl_distribution_name: Ubuntu-22.04
    wsl_distribution_state: run
    wsl_distribution_arch_version: 2

    # Test default user configuration
    wsl_distribution_config_user_default: "ubuntu"
    wsl_distribution_config_user_default_uid: 1000
    wsl_distribution_config_user_default_login_shell: "/bin/bash"
    wsl_distribution_config_user_default_sudo: true

    # Test WSL configuration settings
    ## Automount settings
    wsl_distribution_config_automount_enabled: true
    wsl_distribution_config_automount_mountFsTab: true
    wsl_distribution_config_automount_root: "/mnt/"
    wsl_distribution_config_automount_options: "metadata,uid=1000,gid=1000"

    ## Network settings
    wsl_distribution_config_network_generateHosts: true
    wsl_distribution_config_network_generateResolvConf: true
    wsl_distribution_config_network_hostname: "wsl-ubuntu"

    ## Interop settings
    wsl_distribution_config_interop_enabled: true
    wsl_distribution_config_interop_appendWindowsPath: true

    ## Boot settings
    wsl_distribution_config_boot_systemd: true
    wsl_distribution_config_boot_command: ""

    # Test extra configuration
    wsl_distribution_extra_configs:
      custom_section:
        property1: "value1"
        property2: 123
      another_section:
        setting: "true"
