---
- name: Verify
  hosts: windows
  gather_facts: false
  tasks:
    - name: Check WSL distribution exists
      ansible.windows.win_shell: wsl.exe -l -v
      register: wsl_list
      changed_when: false

    - name: Normalize WSL output
      ansible.builtin.set_fact:
        normalized_wsl_output: "{{ wsl_list.stdout | replace('\u0000', '') }}"

    - name: Verify Ubuntu-22.04 is installed
      ansible.builtin.assert:
        that:
          - "'Ubuntu-22.04' in normalized_wsl_output"
          - "'Running' in normalized_wsl_output"
        fail_msg: "Ubuntu-22.04 distribution is not installed or not running"
        success_msg: "Ubuntu-22.04 distribution is successfully installed and running"

    - name: Verify WSL configuration file exists
      ansible.windows.win_shell: wsl.exe -d Ubuntu-22.04 -u root -- cat /etc/wsl.conf
      register: wsl_conf_result
      changed_when: false

    - name: Normalize WSL config output
      ansible.builtin.set_fact:
        normalized_wsl_conf: "{{ wsl_conf_result.stdout | replace('\u0000', '') }}"

    - name: Verify standard configuration sections
      ansible.builtin.assert:
        that:
          - "'[automount]' in normalized_wsl_conf"
          - "'enabled = true' in normalized_wsl_conf"
          - "'mountFsTab = true' in normalized_wsl_conf"
          - "'root = /mnt/' in normalized_wsl_conf"
          - "'options = metadata,uid=1000,gid=1000' in normalized_wsl_conf"

          - "'[boot]' in normalized_wsl_conf"
          - "'systemd = true' in normalized_wsl_conf"

          - "'[interop]' in normalized_wsl_conf"
          - "'enabled = true' in normalized_wsl_conf"
          - "'appendWindowsPath = true' in normalized_wsl_conf"

          - "'[user]' in normalized_wsl_conf"
          - "'default = ubuntu' in normalized_wsl_conf"
        fail_msg: "Standard WSL configuration sections not found or incorrect"
        success_msg: "Standard WSL configuration sections are correctly set"

    - name: Verify extra configuration sections
      ansible.builtin.assert:
        that:
          - "'[custom_section]' in normalized_wsl_conf"
          - "'property1 = value1' in normalized_wsl_conf"
          - "'property2 = 123' in normalized_wsl_conf"

          - "'[another_section]' in normalized_wsl_conf"
          - "'setting = true' in normalized_wsl_conf"
        fail_msg: "Extra configuration sections not found or incorrect"
        success_msg: "Extra configuration sections are correctly set"

    - name: Verify default user exists
      ansible.windows.win_shell: wsl.exe -d Ubuntu-22.04 -- id ubuntu
      register: user_result
      changed_when: false

    - name: Normalize user check output
      ansible.builtin.set_fact:
        normalized_user_result: "{{ user_result.stdout | replace('\u0000', '') }}"

    - name: Verify default user is properly configured
      ansible.builtin.assert:
        that:
          - "'uid=' in normalized_user_result"
        fail_msg: "Default user 'ubuntu' is not properly configured"
        success_msg: "Default user 'ubuntu' is properly configured"
