---
- name: Verify
  hosts: windows
  gather_facts: false
  tasks:
    - name: Check WSL distribution exists
      ansible.windows.win_shell: wsl.exe -l -v
      register: wsl_list
      changed_when: false

    - name: Normalize WSL output
      ansible.builtin.set_fact:
        normalized_wsl_output: "{{ wsl_list.stdout | replace('\u0000', '') }}"

    - name: Verify Ubuntu-22.04 is installed
      ansible.builtin.assert:
        that:
          - "'Ubuntu-22.04' in normalized_wsl_output"
          - "'Running' in normalized_wsl_output"
        fail_msg: "Ubuntu-22.04 distribution is not installed or not running"
        success_msg: "Ubuntu-22.04 distribution is successfully installed and running"

    - name: Verify WSL configuration file exists
      ansible.windows.win_shell: wsl.exe -d Ubuntu-22.04 -u root -- cat /etc/wsl.conf
      register: wsl_conf_result
      changed_when: false

    - name: Normalize WSL config output
      ansible.builtin.set_fact:
        normalized_wsl_conf: "{{ wsl_conf_result.stdout | replace('\u0000', '') }}"

    - name: Verify configuration content
      ansible.builtin.assert:
        that:
          - "'automount' in normalized_wsl_conf"
          - "'enabled = true' in normalized_wsl_conf"
          - "'systemd = true' in normalized_wsl_conf"
          - "'default = ubuntu' in normalized_wsl_conf"
        fail_msg: "WSL configuration does not contain expected settings"
        success_msg: "WSL configuration is correctly set"

    - name: Verify default user exists
      ansible.windows.win_shell: wsl.exe -d Ubuntu-22.04 -- id ubuntu
      register: user_result
      changed_when: false

    - name: Normalize user check output
      ansible.builtin.set_fact:
        normalized_user_result: "{{ user_result.stdout | replace('\u0000', '') }}"

    - name: Verify default user is properly configured
      ansible.builtin.assert:
        that:
          - "'uid=' in normalized_user_result"
        fail_msg: "Default user 'ubuntu' is not properly configured"
        success_msg: "Default user 'ubuntu' is properly configured"
