---
argument_specs:
  main:
    description: Manage Windows Subsystem for Linux (WSL) distributions
    options:
      wsl_distribution_name:
        type: str
        required: true
        description: >
          Name of the WSL distribution to manage.
          If rootfs is not provided, install the distribution from the MS Store.
          If the distribution is not available in MS Store, this role will fail

      wsl_distribution_web_download:
        type: bool
        default: true
        description: Whether to install the distribution from Microsoft Store

      wsl_distribution_rootfs_path:
        type: str
        required: false
        description: Path or URL to the rootfs archive for custom distribution installation

      wsl_distribution_rootfs_download_path:
        type: str
        required: false
        description: Directory where the rootfs archive will be downloaded when using URL

      wsl_distribution_rootfs_download_checksum:
        type: str
        required: false
        description: Checksum for validating downloaded rootfs archive

      wsl_distribution_rootfs_download_checksum_algorithm:
        type: str
        default: sha256
        choices: [md5, sha1, sha256, sha384, sha512]
        description: Algorithm to use for rootfs checksum validation

      wsl_distribution_import_dir_path:
        type: str
        required: false
        description: Directory where the WSL distribution will be installed

      wsl_distribution_import_bundle:
        type: bool
        default: false
        description: Whether the rootfs archive is an Appx bundle that contains the rootfs

      wsl_distribution_import_vhd:
        type: bool
        default: false
        description: Whether to use VHD format when importing the WSL distribution

      wsl_distribution_arch_version:
        type: int
        default: 2
        choices: [1, 2]
        description: WSL architecture version to use (1 or 2)

      wsl_distribution_state:
        type: str
        default: run
        choices: [run, stop, absent]
        description: Desired state of the WSL distribution

      wsl_distribution_config:
        type: dict
        required: false
        description: >
          WSL distribution configuration settings.
          Config Dictionary is converted to ini format before setting in wsl distribution
