---
argument_specs:
  main:
    short_description: Manage WSL distributions
    description: Manage Windows Subsystem for Linux (WSL) distributions
    options:
      wsl_distribution_name:
        type: str
        required: true
        description: >
          Name of the WSL distribution to manage.
          If rootfs is not provided, install the distribution from online distribution.
          If the distribution is not available online, this role will fail

      wsl_distribution_install_web_download:
        type: bool
        default: true
        description: Whether to install the distribution from Microsoft Store

      wsl_distribution_import_rootfs_path:
        type: str
        required: false
        description: Path or URL to the rootfs archive for custom distribution installation

      wsl_distribution_import_rootfs_download_path:
        type: str
        required: false
        description: Directory where the rootfs archive will be downloaded when using URL

      wsl_distribution_import_rootfs_download_checksum:
        type: str
        required: false
        description: Checksum for validating downloaded rootfs archive

      wsl_distribution_import_rootfs_download_checksum_algorithm:
        type: str
        default: sha256
        choices: [md5, sha1, sha256, sha384, sha512]
        description: Algorithm to use for rootfs checksum validation

      wsl_distribution_import_dir_path:
        type: str
        required: false
        description: Directory where the WSL distribution will be installed

      wsl_distribution_import_bundle:
        type: bool
        default: false
        description: Whether the rootfs archive is an Appx bundle that contains the rootfs

      wsl_distribution_import_vhd:
        type: bool
        default: false
        description: Whether to use VHD format when importing the WSL distribution

      wsl_distribution_arch_version:
        type: int
        default: 2
        choices: [1, 2]
        description: WSL architecture version to use (1 or 2)

      wsl_distribution_state:
        type: str
        default: run
        choices: [run, stop, absent]
        description: Desired state of the WSL distribution

      wsl_distribution_config_user_default:
        description: Override the default user specified in distribution configuration
        type: str
        required: false
        default: root

      wsl_distribution_config_user_default_login_shell:
        description: Login shell for the default user
        type: str
        default: /bin/bash

      wsl_distribution_config_user_default_password:
        description: Password to set for the default user. Setting this will make this role non-idempotence
        type: str
        no_log: true

      wsl_distribution_config_user_default_sudo:
        description: Whether to grant sudo privileges to the default user
        type: bool
        default: false

      wsl_distribution_config_user_default_authorized_keys:
        description: List of SSH public keys to add to authorized_keys for the default user
        type: list
        elements: str
        default: []

      wsl_distribution_config_automount_enabled:
        description: Enable automatic mounting of Windows drives
        type: bool
        default: true

      wsl_distribution_config_automount_mountFsTab:
        description: Enable mounting via /etc/fstab
        type: bool
        default: true

      wsl_distribution_config_automount_root:
        description: Root directory for Windows drive mounts
        type: str
        default: "/mnt/"

      wsl_distribution_config_automount_options:
        description: Mount options for Windows drives, comma separated value
        type: str
        required: false

      wsl_distribution_config_network_generateHosts:
        description: Enable automatic /etc/hosts generation
        type: bool
        default: true

      wsl_distribution_config_network_generateResolvConf:
        description: Enable automatic /etc/resolv.conf generation
        type: bool
        default: true

      wsl_distribution_config_network_hostname:
        description: Set WSL distribution hostname
        type: str

      wsl_distribution_config_interop_enabled:
        description: Enable Windows process interoperability
        type: bool
        default: true

      wsl_distribution_config_interop_appendWindowsPath:
        description: Add Windows PATH to $PATH
        type: bool
        default: true

      wsl_distribution_config_boot_command:
        description: Command to run on WSL startup
        type: str
        required: false

      wsl_distribution_config_boot_systemd:
        description: Enable systemd support
        type: bool
        default: true

      wsl_distribution_extra_configs:
        description: Additional configuration sections and properties to append to wsl.conf
        type: dict
        required: false
