---
dependency:
  name: galaxy
platforms:
  - name: windows
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ${MOLECULE_PROJECT_DIRECTORY}/molecule/inventory.yml
  config_options:
    defaults:
      remote_tmp: C:\Windows\Temp
  vars:
    ansible_host: 127.0.0.1
    ansible_port: "{{ wsl_sshd_port_forward_host_port }}"
    ansible_connection: ssh
  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: port_forward
  test_sequence:
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
