- name: Converge
  hosts: windows
  gather_facts: false
  vars:
    sshd_port: 2222
    distribution: Ubuntu-20.04

  roles:
    - role: vanduc2514.wsl_automation.wsl_sshd
      vars:
        wsl_sshd_distribution_name: "{{ distribution }}"
        wsl_sshd_port: "{{ sshd_port }}"
        wsl_sshd_extra_configs:
          MaxAuthTries: "3"
          LoginGraceTime: "60"
          ClientAliveInterval: "300"
          ClientAliveCountMax: "3"
        wsl_sshd_systemd_service_override: |
          [Service]
          Environment=SSH_OPTS=-o TCPKeepAlive=yes
