- name: Create
  hosts: windows
  gather_facts: true
  tasks:
    - name: Ensure WSL is installed and enabled
      ansible.builtin.include_role:
        name: vanduc2514.wsl_automation.wsl

    - name: Ensure WSL distribution is installed
      ansible.builtin.include_role:
        name: vanduc2514.wsl_automation.wsl_distribution
      vars:
        wsl_distribution_name: Ubuntu-20.04
        wsl_distribution_import_rootfs_path: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-root.tar.xz
        wsl_distribution_import_rootfs_download_path: D:\Ansible\Ubuntu-20.04.tar.xz
        wsl_distribution_import_dir_path: D:\Ansible\Ubuntu-20.04
        wsl_distribution_state: run
        wsl_distribution_arch_version: 2
        wsl_distribution_config_boot_systemd: true
        wsl_distribution_config_network_generate_resolv_conf: true
        wsl_distribution_config_network_generate_hosts: true
