dependency:
  name: galaxy
platforms:
  - name: windows
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ${MOLECULE_PROJECT_DIRECTORY}/molecule/inventory.yml
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
    destroy: destroy.yml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: passwordless
  test_sequence:
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
