- name: Stop wsl distribution
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    state: stop
  when: wsl_distribution_state == "run"
  listen: restart wsl

- name: Run wsl distribution
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    state: run
  when: wsl_distribution_state == "run"
  listen: restart wsl
