---
- name: Ensure WSL distribution state
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    web_download: "{{ wsl_distribution_install_from_store }}"
    rootfs_path: "{{ wsl_distribution_rootfs_path | default(omit) }}"
    rootfs_download_path: "{{ wsl_distribution_rootfs_download_path | default(omit) }}"
    rootfs_download_checksum: "{{ wsl_distribution_rootfs_download_checksum | default(omit) }}"
    rootfs_download_checksum_algorithm: "{{ wsl_distribution_rootfs_download_checksum_algorithm | default(omit) }}"
    import_dir_path: "{{ wsl_distribution_import_dir_path | default(omit) }}"
    import_bundle: "{{ wsl_distribution_import_bundle }}"
    import_vhd: "{{ wsl_distribution_import_vhd }}"
    arch_version: "{{ wsl_distribution_arch_version }}"
    state: "{{ wsl_distribution_state }}"
  when: wsl_distribution_state != "absent"

- name: Create WSL configuration
  vanduc2514.wsl_automation.wsl_file:
    distribution: "{{ wsl_distribution_name }}"
    path: "/etc/wsl.conf"
    content: "{{ lookup('template', 'wsl.conf.j2') }}"
    state: file
    mode: "0644"
  when: wsl_distribution_state != "absent"

- name: Remove WSL distribution if state is absent
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    state: "absent"
  when: wsl_distribution_state == "absent"