- name: Ensure WSL distribution state
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    web_download: "{{ wsl_distribution_web_download }}"
    rootfs_path: "{{ wsl_distribution_rootfs_path | default(omit) }}"
    rootfs_download_path: "{{ wsl_distribution_rootfs_download_path | default(omit) }}"
    rootfs_download_checksum: "{{ wsl_distribution_rootfs_download_checksum | default(omit) }}"
    rootfs_download_checksum_algorithm: "{{ wsl_distribution_rootfs_download_checksum_algorithm | default(omit) }}"
    import_dir_path: "{{ wsl_distribution_import_dir_path | default(omit) }}"
    import_bundle: "{{ wsl_distribution_import_bundle }}"
    import_vhd: "{{ wsl_distribution_import_vhd }}"
    arch_version: "{{ wsl_distribution_arch_version }}"
    state: "{{ wsl_distribution_state }}"

- name: Manage WSL user
  vanduc2514.wsl_automation.wsl_user:
    distribution: "{{ wsl_distribution_name }}"
    name: "{{ wsl_distribution_config.user.default | default(omit) }}"
    state: present
  when:
    - wsl_distribution_state != "absent"
    - wsl_distribution_config.user is defined
    - wsl_distribution_config.user.default is defined

- name: Create WSL configuration
  vanduc2514.wsl_automation.wsl_file:
    distribution: "{{ wsl_distribution_name }}"
    path: "/etc/wsl.conf"
    content: "{{ wsl_distribution_config | community.general.to_ini | replace('True', 'true') | replace('False', 'false') }}"
    state: file
    mode: 0644
  when: wsl_distribution_state != "absent"
