- name: Ensure WSL distribution state
  vanduc2514.wsl_automation.wsl_instance:
    distribution: "{{ wsl_distribution_name }}"
    web_download: "{{ wsl_distribution_install_web_download }}"
    rootfs_path: "{{ wsl_distribution_import_rootfs_path | default(omit) }}"
    rootfs_download_path: "{{ wsl_distribution_import_rootfs_download_path | default(omit) }}"
    rootfs_download_checksum: "{{ wsl_distribution_import_rootfs_download_checksum | default(omit) }}"
    rootfs_download_checksum_algorithm: "{{ wsl_distribution_import_rootfs_download_checksum_algorithm | default(omit) }}"
    import_dir_path: "{{ wsl_distribution_import_dir_path | default(omit) }}"
    import_bundle: "{{ wsl_distribution_import_bundle }}"
    import_vhd: "{{ wsl_distribution_import_vhd }}"
    arch_version: "{{ wsl_distribution_arch_version }}"
    state: "{{ wsl_distribution_state }}"

- name: Manage WSL default user
  vanduc2514.wsl_automation.wsl_user:
    distribution: "{{ wsl_distribution_name }}"
    name: "{{ wsl_distribution_config_user_default }}"
    state: present
  when:
    - wsl_distribution_state != "absent"
    - wsl_distribution_config_user_default is defined
    - wsl_distribution_config_user_default | length > 0

- name: Create WSL configuration file
  vanduc2514.wsl_automation.wsl_file:
    distribution: "{{ wsl_distribution_name }}"
    path: /etc/wsl.conf
    content: "{{ lookup('ansible.builtin.template', 'wsl.conf.j2') }}"
    state: file
    mode: 0644
  when: wsl_distribution_state != "absent"
